### ISSUE TITLE
Requires you to add Gibbon dependancy manually.

### ISSUE THREAD

**Issue by SirRawlins** [sorry-app/devise_campaignable#4]
We recently merged in a PR #1 which added install instructions asking users to add 'Gibbon' to their Gemfile as it wasn't being installed by Bundler as part of the devise_campaignable dependancy tree.

The gemspec does list Gibbon as a runtime dependancy so I'm a little confused as to why Bundler isn't picking it up. I've also noticed that I myself haven't had this issue.

Need to find a way to reproduce the problem and we can then patch things up.

**Comment by SirRawlins** [comment]
I have spoken to a few peers on the #rubyonrails IRC channel and they've added the gem to their bundle and the dependancies appear to have been pulled in just fine.

I wonder if their is a version issue here, perhaps running on slightly older versions of ruby is causing a conflict? There is an open issue on the Gibbon project related to install issues on older rubies.

https://github.com/amro/gibbon/issues/78

**Comment by jaimeiniesta** [comment]
In case it helps, I reproduced this on an app using Ruby 2.1.5, Rails 4.1.12 and Devise 3.4.1, on the `development` environment.

**Comment by SirRawlins** [comment]
@jaimeiniesta thanks - that says it's not likely a version issue as those are very similar versions to what I'm running locally. hmmm. quite peculiar.

**Comment by jaimeiniesta** [comment]
More clues: on both projects that I've seen this behaviour, we were using RVM with a gemset. And it failed both if we run `rails server` or `bundle exec rails server`.

**Comment by SirRawlins** [comment]
@jaimeiniesta thank you. Can you tell me - do you see Gibbon listed in your Gemfile,lock? Do you get any errors when running bundle install?

**Comment by jaimeiniesta** [comment]
Yes, Gibbon appears on Gemfile.lock, and no, I don't get any errors on bundle install.

**Comment by DanBlakeman** [comment]
@SirRawlins We were running Ruby 2.2.1, Rails 4.2.1 & Devise 3.2.0.

I've just emptied my rvm gemset and am currently doing a fresh bundle install to be sure issue still exists. Will let you know once it's finished.

**Comment by jaimeiniesta** [comment]
Good idea, I tried with a fresh gemset but it keeps failing.

**Comment by SirRawlins** [comment]
Cheers for the help in diagnosing this one guys - look forward to hearing your experiences with the fresh install.

**Comment by DanBlakeman** [comment]
gibbon (>= 1.1.5) definitely appears in the gemfile.lock after a fresh install.

The only message i get on bundling that's vaguely relevant is: 

```
Post-install message from gibbon:
IMPORTANT: Gibbon now targets MailChimp API 2.0, which is substantially different from API 1.3.
                             Please use Gibbon 0.4.6 if you need to use API 1.3.
If you're upgrading from <0.5.0 your code WILL break.

```

But even stranger, i don't seem to have the issue anymore!

Unfortunately its been a while since i've worked on this project or with rails, and our client has changed the mailchimp password so i can't confirm whether now its working, or i'd somehow disabled devise_campaignable from running in development...

**Comment by DanBlakeman** [comment]
_Update_: I had an if statement in the model preventing campaignable from being included in development.

Issue still exists after fresh install :(

**Comment by SirRawlins** [comment]
O.k thanks Dan. This really is a strange one, especially as Gibbon is listed in the Gemfile.lock, and gives the post-install note, it's clearly in place by the app cannot see it.

Can you double confirm the error/stacktrace for me?

**Comment by DanBlakeman** [comment]
Sure: 

Error: 

```
NameError in Devise::RegistrationsController#create
uninitialized constant Devise::Models::Campaignable::Adapters::Mailchimp::Gibbon
```

Full trace:

```
devise_campaignable (0.0.4) lib/devise_campaignable/adapters/mailchimp.rb:78:in `api'
devise_campaignable (0.0.4) lib/devise_campaignable/adapters/mailchimp.rb:10:in `subscribe'
devise_campaignable (0.0.4) lib/devise_campaignable/model.rb:33:in `subscribe'
activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.1) lib/active_support/callbacks.rb:228:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
activesupport (4.2.1) lib/active_support/callbacks.rb:506:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:506:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:506:in `each'
activesupport (4.2.1) lib/active_support/callbacks.rb:506:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_create_callbacks'
activerecord (4.2.1) lib/active_record/callbacks.rb:306:in `_create_record'
activerecord (4.2.1) lib/active_record/timestamp.rb:57:in `_create_record'
activerecord (4.2.1) lib/active_record/persistence.rb:502:in `create_or_update'
activerecord (4.2.1) lib/active_record/callbacks.rb:302:in `block in create_or_update'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
activerecord (4.2.1) lib/active_record/callbacks.rb:302:in `create_or_update'
activerecord (4.2.1) lib/active_record/persistence.rb:120:in `save'
activerecord (4.2.1) lib/active_record/validations.rb:37:in `save'
activerecord (4.2.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
activerecord (4.2.1) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
activerecord (4.2.1) lib/active_record/transactions.rb:220:in `transaction'
activerecord (4.2.1) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block in save'
activerecord (4.2.1) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
activerecord (4.2.1) lib/active_record/transactions.rb:285:in `save'
devise (3.5.1) app/controllers/devise/registrations_controller.rb:17:in `create'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.3) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
puma (2.11.3) lib/puma/server.rb:507:in `handle_request'
puma (2.11.3) lib/puma/server.rb:375:in `process_client'
puma (2.11.3) lib/puma/server.rb:262:in `block in run'
puma (2.11.3) lib/puma/thread_pool.rb:104:in `call'
puma (2.11.3) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by jaimeiniesta** [comment]
I have stopped using a gemset, but it keeps failing, here's my stack trace:

```
NameError - uninitialized constant Devise::Models::Campaignable::Adapters::Mailchimp::Gibbon:
  activesupport (4.1.12) lib/active_support/dependencies.rb:519:in `load_missing_constant'
  activesupport (4.1.12) lib/active_support/dependencies.rb:180:in `const_missing'
   () Users/jaime/.rvm/gems/ruby-2.1.5/bundler/gems/devise_campaignable-6b7b95297c46/lib/devise_campaignable/adapters/mailchimp.rb:78:in `api'
   () Users/jaime/.rvm/gems/ruby-2.1.5/bundler/gems/devise_campaignable-6b7b95297c46/lib/devise_campaignable/adapters/mailchimp.rb:10:in `subscribe'
   () Users/jaime/.rvm/gems/ruby-2.1.5/bundler/gems/devise_campaignable-6b7b95297c46/lib/devise_campaignable/model.rb:33:in `subscribe'
  activesupport (4.1.12) lib/active_support/callbacks.rb:429:in `block in make_lambda'
  activesupport (4.1.12) lib/active_support/callbacks.rb:224:in `block in halting_and_conditional'
  activesupport (4.1.12) lib/active_support/callbacks.rb:503:in `block in call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.12) lib/active_record/callbacks.rb:306:in `_create_record'
  activerecord (4.1.12) lib/active_record/timestamp.rb:57:in `_create_record'
  activerecord (4.1.12) lib/active_record/persistence.rb:484:in `create_or_update'
  activerecord (4.1.12) lib/active_record/callbacks.rb:302:in `block in create_or_update'
  activesupport (4.1.12) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.12) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.12) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.1.12) lib/active_record/persistence.rb:103:in `save'
  activerecord (4.1.12) lib/active_record/validations.rb:51:in `save'
  activerecord (4.1.12) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.1.12) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  activerecord (4.1.12) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  activerecord (4.1.12) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  activerecord (4.1.12) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  activerecord (4.1.12) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  activerecord (4.1.12) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (4.1.12) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  activerecord (4.1.12) lib/active_record/transactions.rb:268:in `block in save'
  activerecord (4.1.12) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  activerecord (4.1.12) lib/active_record/transactions.rb:267:in `save'
  devise (3.4.1) app/controllers/devise/registrations_controller.rb:19:in `create'
  actionpack (4.1.12) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.12) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.12) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.12) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.12) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.12) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.12) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.12) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.12) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.12) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.12) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.12) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.12) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.12) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.12) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.12) lib/action_dispatch/routing/mapper.rb:45:in `call'
  actionpack (4.1.12) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.12) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.12) lib/action_dispatch/routing/route_set.rb:692:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  bullet (4.14.0) lib/bullet/rack.rb:12:in `call'
  rack-attack (4.2.0) lib/rack/attack.rb:104:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.12) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.12) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.12) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.12) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.12) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.12) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.12) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.12) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.12) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.12) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  actionpack (4.1.12) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.12) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.12) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.12) lib/rails/engine.rb:514:in `call'
  railties (4.1.12) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
   () Users/jaime/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
   () Users/jaime/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
   () Users/jaime/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by SirRawlins** [comment]
Thanks both. I'm wondering if I'm missing a 'require' line somewhere in the codebase to bring Gibbon in.

If you try and use gibbon from the Rails command line what do you get?

``` ruby
Gibbon::API.new("your_api_key")
```

**Comment by DanBlakeman** [comment]
Good thinking, I was wondering that too...

Doesn't seem the case though? As in rails console:

```
2.2.1 :002 > Gibbon::API.new("your_api_key")
NameError: uninitialized constant Gibbon
    from (irb):2
    from /Users/dan/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
    from /Users/dan/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
    from /Users/dan/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /Users/dan/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/dan/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
    from /Users/dan/Desktop/Dev/lend_and_tend/bin/rails:8:in `<top (required)>'
    from /Users/dan/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/dan/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

**Comment by SirRawlins** [comment]
Hi Dan. In the console that is what I would expect, if you run `require 'gibbon'` first do you still get the error?

**Comment by DanBlakeman** [comment]
Aha! 

Requiring it works:

```
2.2.1 :001 > require 'gibbon'
 => true 
2.2.1 :002 > Gibbon::API.new("your_api_key")
 => #<Gibbon::API:0x007feef2bfd4f0 @api_key="your_api_key", @api_endpoint=nil, @timeout=nil, @throws_exceptions=nil, @default_params={:apikey=>"your_api_key"}> 
```

**Comment by SirRawlins** [comment]
Sweet! O.k so that's our issue - should have spotted that sooner, I'm too used to libs being autoloaded.

Patch inbound.

**Comment by DanBlakeman** [comment]
:+1:  :trophy:

**Comment by SirRawlins** [comment]
O.k just cut version 0.0.5 which explicitly requires gibbon. If you upgrade to the latest gem it should all come to life. Let me know how you get on.

Thanks again for helping solve that one - really appreciated.

**Comment by DanBlakeman** [comment]
Your most welcome, thanks for the patch! 

Just done a fresh install resetting the rvm gemset to be sure. Works fab! :+1:

**Comment by SirRawlins** [comment]
Really great news Dan. Happy chimping!

**Comment by jaimeiniesta** [comment]
Cool, thanks, the new release is working great :)
